<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mdg.Client.Adapter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mdg.Core\Mdg.Core.csproj" />
  </ItemGroup>

</Project>
